[package]
name = "hp00_revolution"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "*", features = ["dynamic_linking"] }
rand = "0.8"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
